name: TTY
google_analytics_id: UA-31255537-1
gems:
  - jekyll-assets
  - bourbon
assets:
  cache: false
  compress:
    css: sass
    js: uglifier
  cachebust: hard
  prefix: ''
  gzip: [ text/css, application/javascript ]
exclude: [components, Rakefile, Gemfile, Gemfile.lock]
